spring:
  # 数据源配置
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://127.0.0.1:3306/smart-medicine?serverTimezone=Hongkong&useAffectedRows=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 邮件配置  邮箱账号 加 授权码
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          # 加密连接
          starttls:
            enable: true
            required: true
          # 安全连接
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    valid: 5
    title: "智慧医药系统 - 用户认证"
    template: "您的动态验证码为：<strong style='color: red'>%s</strong>，%d分钟内有效，若非本人操作，请勿泄露。"
# 日志配置
logging:
  level:
    world.tangjp.dao.mapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云通义千问配置
ai-key: ${AI_KEY}
# 阿里云对象存储配置
oss:
  bucket-name: smart-medicine-sys
  end-point: oss-cn-guangzhou.aliyuncs.com
  access-key: ${OSS_ACCESS_KEY}
  access-secret: ${OSS_ACCESS_SECRET}

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    swagger-model-name: 实体类列表
  basic:
    enable: false
    username: admin 
    password: 123456